### ISSUE TITLE
Glyphs not Characters

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#111]
Here is a simple example of a glyph object:

```
   "fontchars": {
      "0x0020": {
         "objtype": "char",
         "charname": "Space",
         "charhtml": "&#32;",
         "isautowide": false,
         "charwidth": 500,
         "leftsidebearing": false,
         "rightsidebearing": false,
         "ratiolock": false,
         "maxes": {
            "xmax": 0,
            "xmin": 0,
            "ymax": 0,
            "ymin": 0
         },
         "charshapes": []
      },
```

I suggest thinking about the fundamental unit of a font as glyphs, not characters. Eg,

```
   "glyphs": {
      "space": {
         "objtype": "glyph", # could probably be made implicit?
         "unicode": "0x0020",
         "charhtml": "&#32;", # ditto
         "isautowide": false,
         "charwidth": 500,
         "leftsidebearing": false,
         "rightsidebearing": false,
         "ratiolock": false,
         "maxes": {
            "xmax": 0,
            "xmin": 0,
            "ymax": 0,
            "ymin": 0
         },
         "charshapes": []
      },
```

This change would also mean changing the `Characters` panel to the `Glyphs` panel, `Character Edit` to `Glyphs Edit`, etc :)

**Comment by davelab6** [comment]
I'm curious if you have any data of how many actual users there are making fonts they care about yet? :)

**Comment by mattlag** [comment]
I don't - but telemetry would be very interesting to track.  Right now the best I have is unique visitors to the /online or /sandbox pages... not the same as actual users making fonts they care about, though.

I think maybe the best I could do is count the number of times somebody saves a project file or exports a font.  Moving forward this would be good information to have.  I'll think about it...

**Comment by davelab6** [comment]
I think before spending a lot of time on beta upgrade scripts, it would be wise to know how much user demand there actually is for such a script. Assuming all versions of glyphr can produce OTF binaries, once glyphr can load OTF binaries, then that seems like the lease effort path to data upgrades :)

**Comment by mattlag** [comment]
Done for V1
