### ISSUE TITLE
When directing people to contribute, provide direct links

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#112]
On the homepage you say,

> or use glyphrstudio.uservoice.com to vote for new features. 

Instead, could you say

> or vote for new features on [Github issues](https://github.com/mattlag/Glyphr-Studio/issues?q=is%3Aopen+is%3Aissue) with a +1 comment

**Comment by davelab6** [comment]
I closed this as the homepage changed, but then I saw there were 2 places in the app asking users to contribute with feedback. 

In both places, lets add a direct link with `target=_blank` attribute to open in a new window to the uservoice and github issues pages 

- [ ] `About`

![screen shot 2015-05-09 at 3 23 02 am](https://cloud.githubusercontent.com/assets/261579/7548294/e1bad016-f5fa-11e4-9f14-35fd9e38d61e.png)

- [ ] `give back!`

![screen shot 2015-05-09 at 3 23 13 am](https://cloud.githubusercontent.com/assets/261579/7548295/e1bc4586-f5fa-11e4-9c5f-56f1fd3231ce.png)

**Comment by mattlag** [comment]
I had been using _new, but I just learned it's not correct.  I changed every link to _blank, the default behavior for all links should be (and now is) a new window.

fixed in v1.00.02

**Comment by davelab6** [comment]
I also like to use `style="cursor: alias:` to change the pointer to show it will open in a new window
