### ISSUE TITLE
Kerning: Show Glyphs using Opacity

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#119]
In the kerning view, all the glyphs in a class are shown stacked on top of each other, at 100% opacity. This doesn't look great to me. 

I suggest using an opacity of say 20% for each glyph, so that a single glyph's area is clearly visible. 

Other editors do this, here's Glyphs:

![](http://www.glyphsapp.com/content/images/blog-screenshots/dia-9.PNG)

**Comment by mattlag** [comment]
This is done in v1.04
