### ISSUE TITLE
Boolean Tools (Knife, Combine/Remove Overlaps) and Measure Tool

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#125]
### Knife Tool

When drawing glyphs, I frequently want to slice a drawn shape into pieces with a 'knife' tool, where I click and drag a line between two points, and 
- [ ] if the knife cuts across just 1 edge of a shape, it make the contour open and adds 2 points at that location on the contour
- [ ] if the knife cuts across 2 edges of a shape, the result is 2 shapes. This implies boolean operations... which leads to

### Combine Shapes

Also known as "Remove Overlaps" and important as an option for https://github.com/mattlag/Glyphr-Studio/issues/108 as binary OpenType font's are not meant to have overlapping contours

### Measure Tool

This works interactively in a way similar to a knife tool. Inkscape has a nice one - https://www.youtube.com/watch?v=LjfVyGbHsdc - which measures each intersection with a shape path

(I guess that http://paperjs.org/ will make it easier to do these things...)

**Comment by raphaelbastide** [comment]
+1 for measure tool

**Comment by mattlag** [comment]
###Boolean Tools
- [ ] Unite (Two shapes become one)
- [ ] Intersect (Save the overlapping area)
- [ ] Exclude (Two shapes result in the non-overlapping area)
- [ ] Subtract Front (Top shape cuts away the bottom shape)

Also Consider:
- [ ] Subtract Bottom (Bottom shape cuts away from the top)
- [ ] Divide (Three shapes result, the overlapping area, plus two non-overlapping areas)

###Measure Tool
- [ ] Measure any space between two clicks
- [ ] Measure easily between two points (possibly happens automatically on multi-select points)
- [ ] Measure easily between two spots on a curve

###Knife Tool
