### ISSUE TITLE
Linked Shapes: Multi-contour & Transformable

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#129]
In the http://glyphrstudio.com/sandbox/ example font, its weird that the `O` is actually 2 linked shapes, an inner and outer

Also, its weird that you can't transform a linked shape (eg, scale it 150% taller and 110% wider) 

The OpenType file format has 'components' which allow for these; components are really merely links to unencoded glyphs, with transformation attributes for the scaling/rotation applied

**Comment by davelab6** [comment]
https://github.com/nodebox/opentype.js#features says "support for composite glyphs" :)

**Comment by mattlag** [comment]
Thanks, i'll look into how this is done before I do this improvement.  I don't want to invent a new way of doing something that already exists :-)

**Comment by mattlag** [comment]
Checklist:
- [ ] Linked Shapes have multiple contours
- [ ] Linked Shape Instances can be Scaled (delta width / delta height)
- [ ] Linked Shape Instances can be Translated (moved: delta x / delta y)

Lower priority:
- [ ] Linked Shape Instances can be flipped (flip horizontal / flip vertical)
- [ ] Linked Shape Instances can be rotated (degrees)

**Comment by mattlag** [comment]
Besides rotation, all of this is done in V1 with Components

**Comment by davelab6** [comment]
Awesome! I'm curious, why is rotation left out? :)

**Comment by mattlag** [comment]
Rotation is outside my existing shape transformation functionality, and UI controls.  With rotation, i'll have to create new rotate handles on the canvas, and on the back end, dip into matrix transform (I think).  Currently with stretch / translate / flip, those are all just 'simple' math applied to points and handles.  I basically just took path methods that already existed, and exposed them up appropriately to the Glyph level.

**Comment by davelab6** [comment]
I think pens might help with this :)
