### ISSUE TITLE
Change the sandbox font?

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#135]
I know this may be a heretical and unwanted suggestion.... :) 

I suggest changing the sandbox font to a really good looking libre font. 

I've found the current sandbox's font's use of components for counters very strange. 

I suggest specifically Merriweather, as it has many straight lines and clean, direct curves - so its fun to mess around with :)

**Comment by mattlag** [comment]
I'm going to fold this under #156 - i'm going to stop shipping the /sandbox/ version and put it in as an option to open an existing font/project on the first page
