### ISSUE TITLE
Save / Export confusion

### ISSUE THREAD

**Issue by raphaelbastide** [mattlag/Glyphr-Studio#145]
I understand that exporting a font and saving a project are different. I suggest to point out the differences on the export page:
> By exporting this font, you will lose linked shapes and (…). Chose to *save* the project in order to be able to find back your modifications.

**Comment by mattlag** [comment]
Good idea - in the future there will even be more differences between SVG vs. OTF etc.

**Comment by mattlag** [comment]
Done in V1!
