### ISSUE TITLE
Feature: autosave or save suggestion

### ISSUE THREAD

**Issue by raphaelbastide** [mattlag/Glyphr-Studio#146]
What about a save suggestion option in the project’s settings? It can just prompts a small non-obtrusive tooltip containing the .txt download link each X minutes? Or it can make the floppy disk icon breathing (blinking gently)…

Autosave could be a neater solution because transparent, but I am not sure it is possible with in-browsers apps.

**Comment by mattlag** [comment]
I'm going to close this and merge it with another bug, #59 which is going to use HTML5 local storage.  Local Storage is persistent per computer, and is a more streamlined option than .txt downloading.
