### ISSUE TITLE
Use semver.org versioning

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#148]
I recommend using www.semver.org versioning, so that the next release will be 0.5.3 :)

**Comment by mattlag** [comment]
I've been using the Minor and Patch digis as if they were Major and Minor while in Beta.  The only thing, in my mind, that is keeping me from putting a v1.0.0 on this is "Export OTF".  There is lots of work left to do, but once that happens i'm going to put a v1 on it, then follow Semantic Versioning like it was intended.

I'm also thinking about drastically updating my ship process.  I feel like it's too slow right now, even though I ship betas every few months.  I'm thinking about shipping every time I do any kind of minor feature, so in this case i'd be shipping 1.001.0 / 1.002.0 / 1.003 etc... every few weeks (or however long it takes to do that particular work item).

Also, I would change to the format "Beta 5.3" = v5.3.0-beta, but I already have internal version checking going for backwards and forwards compatibility, so i'm just going to stick with it :-)
