### ISSUE TITLE
Rotation tool

### ISSUE THREAD

**Issue by raphaelbastide** [mattlag/Glyphr-Studio#149]
A rotation tool is needed for basic shapes and linked shapes as well.

**Comment by davelab6** [comment]
I wonder if this can be best done with Pens - https://github.com/mattlag/Glyphr-Studio/issues/157 - the power of pens is seen in https://github.com/loicsander/Robofont-scripts/tree/master/PenBallWizard :)

**Comment by mattlag** [comment]
This is done!
