### ISSUE TITLE
Ship Version 1

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#158]
- [x] Update Website
- [x] Update Readme
- [x] Blog Post
- [x] Remove /sandbox directory
- [x] Drop the -alpha form the version number
- [x] Create help documentation system
- [x] Finish Components Feature
- [x] Finish Import/Export OTF Feature

**Comment by ronoppenheimer** [comment]
I can work on the Readme and and add a "New Features To Come" section, and I could help update the website, potentially writing a blog post. Is the homepage of glyprstudio.com editable with this repository?

**Comment by mattlag** [comment]
Hi Ron

Updating the Readme would be good - the one other big feature that I decided to do for V1 is enabling Components (which is replacing Linked Shapes).  Components drastically change most of the underlying code, and the structure of Glyphr Studio Project file, so I figured it would be good to get these big changes in before V1.  That, and Exporting to OTF via OpenType.js.  A draft blog post could also be helpful.

Unfortunately, the website is still privately hosted and my working files are just on my computer, not in a repository.  At some point i'll create a new site for them, but probably not yet.

If you have some cycles, there is something else that could help immensely.  For V1 the Help page was removed from the Glyphr Studio project, and I actually started a whole new repository for a multi-page site.  It's here: https://github.com/mattlag/Glyphr-Studio-Help  so far, it's just been me writing and proofreading these articles.  So if you want, you could give them a second read, and any feedback here would be **much** appreciated.  The raw articles are in the /articles/ directory, which is where edits happen.  The build process adds headers, footers, and styles, and creates the individual .html pages for the site (which is hosted on github pages).

Thanks so much for offering to help! It's fantastic!

**Comment by ronoppenheimer** [comment]
Alright, I saw the help repository a few days ago, I'll start by going through and proofreading all those articles and adding to them as necessary (I've spent a solid week just using Glyphr Studio to know how it runs). 

I'd happily draft a blog post afterwards, so you're planning on trying to push Exporting to OTF via OpenType.js before V1?

**Comment by ronoppenheimer** [comment]
Drafted Blog Post (Created after basing it off of some past ones):

<b> Version 1 Has Arrived! We are all jumping up and down! </b>

After 5 years of hard work and 5 released betas, we've finally made it down the road to the release of Version 1! Try it out now at <link> glyphrstudio.com</link>!

Some of the major new features that have finally made their appearance Include:
• Exporting to OTF via OpenType.js - You can now export your fonts as OpenType font files and TrueType font files!
• Components (replacing Linked Shapes) - <not sure what to put here>

Minor new features:
* <again, not quite sure what to put here>

Reminders:
• The help documentation has moved to its own <link>Git Hub Repository</link> and will be published to <link>glyphrstudio.com/help</link>
• Sandbox has been removed - <add whatever you'd like here>

**Comment by mattlag** [comment]
Thanks, Ron, this is a great start!
