### ISSUE TITLE
Black space

### ISSUE THREAD

**Issue by jjjlllnnn** [mattlag/Glyphr-Studio#161]
Most of the time when exporting the svg font and then converting to otf, the space appears as a black block. The only way not to have this problem is to use another font software to delete it at the end, which is quite a failure.

**Comment by mattlag** [comment]
Sounds like the 'notdef' glyph is getting exported to the space glyph.  I'll look into it.  What service are you using to convert SVG to OTF?  If possible, could you send me an example SVG file for testing?

**Comment by jjjlllnnn** [comment]
Ok, it seems it that, really strange, using another service won't make this problem, my bad.

**Comment by mattlag** [comment]
No problem - thanks for looking into it!
