### ISSUE TITLE
Rebrand with new logotype, logo?

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#177]
Similarly to https://github.com/mattlag/Glyphr-Studio/issues/135 when I look at the 1.0 demo, the Modegg based logotype and logo has, for me, room to improve - so I thought I'd open an issue to at least raise the topic :) 

I think the 2 core elements of a brand are a color, and a typeface. While I'm advocating to change the type, I like the blue/white/grey colors. 

Just brainstorming, these colors remind me of the common 'blueprint' concept:

![348340](https://cloud.githubusercontent.com/assets/261579/7548005/58bddbd6-f5f1-11e4-8f44-2e01fb91997f.jpg)
![image](https://cloud.githubusercontent.com/assets/261579/7548006/58bfae66-f5f1-11e4-94fa-84c3582dd347.jpg)
![yahh](https://cloud.githubusercontent.com/assets/261579/7548008/58c7f238-f5f1-11e4-95cf-eb2567e33346.jpg)
![twitterlogo_1](https://cloud.githubusercontent.com/assets/261579/7548007/58c4252c-f5f1-11e4-8f86-46fd0c4933a1.jpg)

Also, I think a while back, @mekkablue chatting with @mattlag about the potential similarity of the name to www.glyphsapp.com and so I think sticking with the lowercase 'g' and avoiding a big cap 'G' logo would be kind to their Glyphs App project, which just rebranded with this logo:

![screen shot 2015-05-09 at 2 16 46 am](https://cloud.githubusercontent.com/assets/261579/7548014/857d3bbc-f5f1-11e4-80ea-1fa7120cdc91.png)![screen shot 2015-05-09 at 2 16 39 am](https://cloud.githubusercontent.com/assets/261579/7548015/8595a508-f5f1-11e4-8f75-8211aa6f52bc.png)

**Comment by mattlag** [comment]
closing old issues - sticking with the branding.  I like it :-)

**Comment by davelab6** [comment]
Okay cool :)
