### ISSUE TITLE
Bitesize: Start App with New Path Shape active, not Path Edit tool

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#178]
When you first load glyphr, you can't draw anything! :)

![screen shot 2015-05-09 at 2 35 23 am](https://cloud.githubusercontent.com/assets/261579/7548092/2d6d2222-f5f4-11e4-93f1-7723c96b753f.png)

You have to realise to need to switch to the New Path Shape tool:

![screen shot 2015-05-09 at 2 35 33 am](https://cloud.githubusercontent.com/assets/261579/7548093/2d8a1c38-f5f4-11e4-81ed-6089ff4c774c.png)

**Update** Hah! I realised that I intuitively went to the 'add point' tool, but in fact you anticipated that I'd do that and autoswtich me to the New Shape Tool when I click a coordinate that isn't on a path. :)

**Comment by mattlag** [comment]
I set the default to actually look to see if there are any paths - if there are it stays on the pen tool, if there aren't it switches to the new path tool.

fixed in v1.00.01
