### ISSUE TITLE
Initial screen: Use real tabs, not pill tabs (that look like buttons)

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#184]
As per [Steve Krug](https://www.sensible.com/dmmt.html), when I open Glyphr, I click the 'new' element which looks to me like a button, but actually its a tab, and then I have to think again and click the blue `start a new font from scratch` button:

![screen shot 2015-05-09 at 3 37 10 am](https://cloud.githubusercontent.com/assets/261579/7548338/b81be28e-f5fc-11e4-9c4e-b8bf1ad9a29f.png)

- [ ] I suggst the 3 pill tabs look like tabs, as then I wouldn't get confused about which element is the action button :)

- [ ] Also the button should be placed to the right of the input to show their relation

**Comment by mattlag** [comment]
Bug Cleanup - this was totally done a long time ago.
