### ISSUE TITLE
Can't get out of components or kerning without creating some

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#186]
When I start a new project, click the Glyphr icon at top left, enter components or kerning or ligature windows, then I can't get out of either of them (by clicking the glyphr icon again, or the choose icon) without create a component or kern pair or ligature. Once I add one, the other toolbar buttons appear, and work, and those 2 that I saw initially also work.

**Comment by mattlag** [comment]
fixed in 1.00.01
