### ISSUE TITLE
Show 'undo' butter bars after actions, instead of confirm dialogs before actions

### ISSUE THREAD

**Issue by davelab6** [mattlag/Glyphr-Studio#189]
I found a confirm dialog, triggered by deleting a kerning pair:

![screen shot 2015-05-09 at 4 35 41 am](https://cloud.githubusercontent.com/assets/261579/7548524/ea1a41ce-f604-11e4-8425-690e6f4df3c6.png)

I think its much better to show 'undo' butter bars after a potentially unintended or reconsiderable action, instead of confirm dialogs before the action. 

Google Mail famously does this with sending and deleting: 

![screen shot 2015-05-09 at 4 37 20 am](https://cloud.githubusercontent.com/assets/261579/7548532/1c5f3ee6-f605-11e4-8cf5-a86515242718.png)

I also found that in Glyph Edit, the Attribute, Actions, Shape, Delete button does **not** raise a confirm dialog. I suggest all delete actions raise a undo butter bar. 

However, the butter bar can fade away on a time, or the next action, or on the user dismissing it, depending on how serious the action is.

**Comment by mattlag** [comment]
This is done in v1.04
