### ISSUE TITLE
Export OTF does not reflect changes unless the font name changes

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#194]
This is a bug, but for some reason if you make changes and export an OTF file after each change, your changes aren't saved to the OTF file unless the Font Name is also changed to something different...

Investigating now...

**Comment by mattlag** [comment]
But only seems to happen with the Merriweather Sans example...

**Comment by marlun** [comment]
Export to OTF stopped working for me too today but after changing some settings (project name, font name and font style) it worked.

**Comment by mattlag** [comment]
Yeah, I'm pretty sure this is still a bug, and i'm looking into it.  My current thought is that it only happens  if you import a font, work on it, export it, then import a font again with the same name... it seems to be stuck exporting the font you imported the first time...

Which is very strange. Changing some metadata seems to re-enable you to export, but obviously this isn't a fix. @marlun let me know if you discover anything else :-)

**Comment by mattlag** [comment]
Very strange bug, but it's mitigated now (not fixed) - exporting should work every time.

**Comment by marlun** [comment]
I was importing an existing font so that probably what I was experiencing :+1:
