### ISSUE TITLE
Exported glyph names

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#196]
- [x] `GlyphOrder` table shows all the glyph names are written using long descriptive names, like `<GlyphID id="94" name="Right Curly Bracket"/>`. For a binary export, this isn't ideal; in a production font file, the glyph names should follow the https://github.com/adobe-type-tools/agl-aglfn specification. 

Additionally, this suggests that the Glyphr API ought to support the 3 kinds of glyph names, `glyph.name_export`, `glyph.name` and `glyph.name_description`, for the glyph names used for export, the glyph names used commonly by designers (eg, following the glyphsapp conventions, eg Џ: `uni040F`, `Dzhe-cy`, `Cyrillic Capital Letter Dzhe`

- [ ] Some glyphnames become `<GlyphID id="96" name="[name not found]"/>` which suggests there's a bug in the name parsing

**Comment by mattlag** [comment]
Pulled out from #176 from @davelab6

**Comment by davelab6** [comment]
These long glyph names crashe fontforge :)

**Comment by mattlag** [comment]
I've stored the short AGLFN names, and I can put them into the OTF save process.  Do you know how long the names can be without crashing FontForge?  The AGLFN does not cover the full Unicode BMP... if there is no AGLFN name for an exported font, I'd like to fall back to the long names I'm currently using, but maybe I can cut the name down so that it doesn't cause errors...

**Comment by mattlag** [comment]
The AGLFN names are now used by default on Export OTF.  If there isn't an AGLFN name that's found, I fake one by removing 'Latin ' from the long name, removing spaces, and cutting it down to 20 characters (which seems to be the longest AGLFN name there is).
