### ISSUE TITLE
Chooser Panel is sluggish while displaying lots of Glyphs

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#203]
At the moment the Chooser Panel just blindly assembles thumbnails for all the Glyphs in the font.  For large fonts with around 300+ Glyphs this starts to introduce performance issues.

Maybe introduce some sort of paging or progressive loading for this panel that is more performant.

-----

Working on solution
- [x] Loading the glyph chooser panel does not block the UI
- [x] Add range chooser so not all glyphs are displayed
- [x] Test range chooser in Dialog Boxes
- [x] Add auto-grouping to custom ranges when fonts are imported

**Comment by louisremi** [comment]
I've been facing this problem, trying to export fonts from Prototypo to Glyphr. Even with 50-100 glyphs.
There are two different issues here:
  1. Scrolling the list of glyphs is sluggish. Probable causes :
    - the extremely high number of DOM nodes in this list, and the depth of the DOM tree. You should try reducing both (by getting rid of the individual tables used for each glyph, using css layout instead, for example),
    - the use of inline svg. Investigate drawing all glyphs to one large canvas and using it as a sprite-sheet.
  2. loading the list of glyphs takes up to several seconds, making the whole UI unresponsive in the meantime. Probable cause (apart from the fact that too many DOM nodes are created) :
    - the component is recreated form scratch every time it is used. Only the glyphs that have been touched should be updated.

**Comment by louisremi** [comment]
Profiling the app revealed another potential offender: https://github.com/mattlag/Glyphr-Studio/blob/master/dev/js/framework_events_mouse.js#L63

You shouldn't touch the DOM on every event, especially mousemove. I'm not sure what behavior you're trying to work around here, maybe I can help you find a more efficient alternative.

**Comment by louisremi** [comment]
The most expensive operation by far is `make_NavPanels_Popin` which redraws the glyph chooser on every every frame through `redrawUnit` and `update_NavPanels`. I'm sure there's a way to avoid this operation. It might help if you tried to recall why you felt `update_NavPanels` was needed on every redraw.

**Comment by mattlag** [comment]
Yes, I've known this was pretty bad for a while.  My philosophy is to focus on features, not perf, at the beginning... then see how it goes in the wild before I do perf improvements (maybe not the best strategy, but there it is).

To answer some of your "why?" questions:
Updating the whole panel was the easiest way to update a glyph.  I still want - when a glyph is being edited - for the thumbnail to also update.  But this could probably wait for a mouseup event as opposed to every single mousemove event.  And I could target the single glyph, as opposed to the whole panel.  It's the shotgun technique, as opposed to a sniper rifle :-)

for #L63 and #L327 Chrome had a behavior where the cursor was set to a text-select bar during drag - I may be able to get rid of this all together now that I use custom cursors.

Thank you very much for looking into this!  I think the Prototypo + Glyphr Studio bridge is awesome, so i'll try and fix these in v1.02 which i'm working on now.

**Comment by louisremi** [comment]
> [...] But this could probably wait for a mouseup event as opposed to every single mousemove event.
> [...] I may be able to get rid of this all together now that I use custom cursors.

Yes, I guess theses two changes would already help a lot!
Thanks for taking care of it : )

**Comment by mattlag** [comment]
Just out of curiosity - what do you use to profile performance?  I'm using Chrome Dev Tools - but i'd be interested if there is another / easier / better way.

**Comment by louisremi** [comment]
I'm using Chrome Dev Tools as well, but I've noticed lines of code such as `// debug('REDRAW UNIT DONE\t' + (Date.now() - start) + ' ms\n::::::::::::::::::::::\n\n');` which could indicate that you're using Chrome's built-in profiler. I could record myself using it on Glyphr if it can help.

**Comment by mattlag** [comment]
:-) Those lines of code are over a year old, and in that time i've learned to use the profiling tools.  Thank you, though.  Debugging my redraw function with only console.log was pretty difficult, but it forced me to look for something better.  I wasn't even using the console's timer function :-D this is the way I learn things - the hard way.

Thanks for the offer to help, though - it is much appreciated.

**Comment by louisremi** [comment]
: )

**Comment by mattlag** [comment]
Moving this to a patch - don't want it to hold up v1.02

**Comment by mattlag** [comment]
I decided to keep the current SVG implementation for the thumbnails.  They were originally canvas thumbnails, but it took one pass to populate the DOM with the canvases, then another to draw to them... also kind of slow.  But, one big change is that populating the panel does not block the rest of the UI.  So it's not any faster, but also it doesn't hold everything else up.

Also added paging, basically, for any range of Glyphs - choose which range you want from a dropdown, as opposed to stacking all Glyphs into one panel.

Seems to be going well so far, if not i'm open to re-visiting this as well.
