### ISSUE TITLE
clipping a shape with another shape

### ISSUE THREAD

**Issue by gambhiro** [mattlag/Glyphr-Studio#206]
How do you create r from n, or c from o?

Copying one shape, creating a clipping shape, and taking their boolean difference comes to mind.

**Comment by mattlag** [comment]
All Boolean operations are being tracked in #153 - at the moment the plan for v1.03 is multi-select path points, and v1.04 will be Boolean operations... so it will happen soonish!

**Comment by gambhiro** [comment]
Awesome! Glyphr will be _neat_.

In FontForge (even in the latest) the SVG editing is really only enough to modify shapes. In Inkscape there is that feeling that one has to abuse the features to create consistent glyphs.

The Glyphr interface is already a relief!

**Comment by mattlag** [comment]
:-D Awesome!  Thank you for all the feedback - a lot of the features that Glyphr Studio already has are from ideas and help from the community, so it's always appreciated.

One of the scenarios i'm really trying to nail is closing the gap between Inkscape/Illustrator and Glyphr Studio.  Our primary "hobbyist font designer" person, in my mind, is a graphic designer that wants to make the leap to font design... making that easy is a mix of standard font design stuff, mixed with standard graphic design stuff.
