### ISSUE TITLE
Combine two paths / Use boolean subtraction to combine two paths with opposite winding

### ISSUE THREAD

**Issue by gambhiro** [mattlag/Glyphr-Studio#207]
Short of #206, for a case like creating c from o:

The o is an outer oval and inner oval. One could add extra vertices on the left side, delete the edges, and make edges between the two cut ovals, effectively closing it up as a new shape.

**Comment by mattlag** [comment]
I'm going to rename this - it's a great idea, but on the back end it is quite different than boolean operations.  I totally get your scenario, though.

The inner shape (in this example) would also have to have it's winding reversed to match the outer (or visa-versa) - plus combined with parts of the shape used to make the cut.

**Comment by mattlag** [comment]
This is covered in #153
