### ISSUE TITLE
The font parse by opentype seem to have changed format

### ISSUE THREAD

**Issue by FranzPoize** [mattlag/Glyphr-Studio#219]
The format of the font object parsed by the opentype lib seems to have changed between the last modification on io_otf_import.js

The font.glyphs object is not an array containing all the glyphs. It's now a GlyphSet following this schema:
```js
font: {
  glyphs: {
    font: {},
    glyphs: {
      0: Glyph,
      1: Glyph,
      2: Glyph,
      3: Glyph,
      4: Glyph,
      ...
    }
    length: Number
}
```

The io_otf_import.js fails on line 99 right now because it's trying to access ```font.glyphs[c]``` with ```c = 0``` which does not exist.

Here is a propose fixed:
* Transforming the ```font.glyphs.glyphs``` object into an array (I don't see any point to it being a object)
* Fixing the erroneous accesses to ```font.glyphs```.

Here is a commit on my fork of the fix :
https://github.com/FranzPoize/Glyphr-Studio/commit/336596b6a2fbe4ce956f5b429080c4b5a3bb4278

**Comment by mattlag** [comment]
Thanks for catching this! I ended up having to go a slightly different route.  The glyphr studio font import function was actually using a destructive process to handle the font.glyphs.glyphs array.  Your fixed worked for normal glyphs, but composite glyphs actually referenced the font.glyphs.glyphs array to get their linked pieces - and as the Glyphr Studio code was shortening the array during import, those referenced glyphs actually became moving targets.

Anyway, i just made a copy of the opentype.js array and destroyed that one instead :-) I'm finalizing the fix and I should be pushing it out today or tomorrow!

**Comment by mattlag** [comment]
Fixed in v1.04.00 - just pushed live to glyphrstudio.com/online

Thanks again!

**Comment by FranzPoize** [comment]
Thanks for the fix. By the way we're super happy about the performance gain since 1.02. Thanks for your hard work and keep it up :D

**Comment by mattlag** [comment]
Oh good! It was just a few small improvements - feedback is always appreciated!
