### ISSUE TITLE
Cannot select path points after undo (Ctrl+Z)

### ISSUE THREAD

**Issue by iwalpola** [mattlag/Glyphr-Studio#228]
In the production version of glyphrstudio, I cannot select path point after performing an undo action.
Steps to fail:
1) Load Material Design webfonts.svg file, specifically one glyph from it (F4F6).
2) Successfully select and delete path point
3) Perform Undo
Result: cannot select path points

**Comment by mattlag** [comment]
Looking into this today - thanks...

**Comment by mattlag** [comment]
Fixed in v1.04.06 and live at glyphrstudio.com/online
