### ISSUE TITLE
Import / Export Ligatures

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [mattlag/Glyphr-Studio#231]
Hi, have you got any plan on adding support for import/export of Components, Ligatures and Kern Pairs, If these features were added it would replace tools like fontforge for font editing. keep up the good work. :+1:

**Comment by mattlag** [comment]
The answer is **Yes** we do plan on it - unfortunately, we use Opentype.js library to save font files.  Right now they don't have support for Components / Ligatures / Kerning, so Glyphr Studio doesn't support it.  As soon as they add support, so will we.

This is, in my opinion, a major issue... but there is not a lot I can do.  If you know of any Devs that could contribute to the OpenType.js project, that would be the way to go.
