### ISSUE TITLE
Edit history doesn't update upon clicking on undo

### ISSUE THREAD

**Issue by mechanicious** [mattlag/Glyphr-Studio#237]
![image](https://cloud.githubusercontent.com/assets/8450319/14410164/4fc1f7d8-ff28-11e5-8fd4-9e6cb8db4a16.png)

When undo is clicked it will update canvas but won't update the Edit History Panel (therefore Edit History doesn't stay synchronized with what's going on the canvas). Edit History will only update itself when clicked on the canvas.

**Comment by mattlag** [comment]
redraw optionally takes an arg to only update the panel, or only update the canvas. I'll take a look, this is probably the issue.
