### ISSUE TITLE
glyphs panel disappears when removing all canvas points

### ISSUE THREAD

**Issue by mechanicious** [mattlag/Glyphr-Studio#240]
To reproduce: add a point and remove it by clicking on it and pressing the `delete` key.

![image](https://cloud.githubusercontent.com/assets/8450319/15166120/161b750c-171c-11e6-9907-83334085545a.png)

In case someone will have trouble with it: undo the last action for the glyphs panel to reappear.

**Comment by mattlag** [comment]
Fixed in v1.07.03
