### ISSUE TITLE
Multi-Select Shapes & Points

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#74]
Multi-select shapes happened in v1.01
Multi-select points is scheduled for v1.02

**Comment by raphaelbastide** [comment]
+1!

**Comment by mattlag** [comment]
This is a big thing that needs to happen.  It's a prerequisite for Boolean operations as well.

**Comment by jjjlllnnn** [comment]
+1

**Comment by davelab6** [comment]
This seems very high priority to get real work done :)

**Comment by mattlag** [comment]
I agree, I think i'm going to do this for v1.01

**Comment by mattlag** [comment]
:shipit:

**Comment by davelab6** [comment]
:8ball:

**Comment by davelab6** [comment]
cc @felipesanches @marcelommp
